version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo Checkpoint crossed - printed even if phase fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - mvn clean
    finally:
      - echo Checkpoint crossed - printed even if phase fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
    finally:
      - echo Checkpoint crossed - printed even if phase fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - target/ROOT.war
    - appspec.yml

cache:
  paths:
    - '/root/.m2/**/*'